<select class="selectpicker" id="player{{ $playerNumber }}CharacterSelect">
    <option value="1">Bowser</option>
    <option value="2">Captain Falcon</option>
    <option value="3">Donkey Kong</option>
    <option value="4">Dr. Mario</option>
    <option value="5">Falco</option>
    <option value="6">Fox</option>
    <option value="7">Game And Watch</option>
    <option value="8">Ganondorf</option>
    <option value="9">Ice Climbers</option>
    <option value="10">Jigglypuff</option>
    <option value="11">Kirby</option>
    <option value="12">Link</option>
    <option value="13">Luigi</option>
    <option value="14">Mario</option>
    <option value="15">Marth</option>
    <option value="16">Mewtwo</option>
    <option value="17">Ness</option>
    <option value="18">Peach</option>
    <option value="19">Pichu</option>
    <option value="20">Pikachu</option>
    <option value="21">Roy</option>
    <option value="22">Samus</option>
    <option value="23">Sheik</option>
    <option value="24">Yoshi</option>
    <option value="25">Young Link</option>
    <option value="26">Zelda</option>
    <option value="27">Random</option>
</select>
